apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
commonLabels:
  app.kubernetes.io/name: talos
  app.kubernetes.io/component: node
patches:
- target:
    group: apps
    version: v1
  patch: |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: node
    spec:
      template:
        spec:
          containers:
          - name: talos
            image: ghcr.io/talos-systems/talos
            volumeMounts:
            - name: var-lib-kubelet
              mountPath: /var/lib/kubelet
            - name: var-lib-containerd
              mountPath: /var/lib/containerd
            - name: var-lib-etcd
              mountPath: /var/lib/etcd
            - name: etc-cni
              mountPath: /etc/cni
            - name: run
              mountPath: /run
            - name: system
              mountPath: /system
            env:
            - name: PLATFORM
              value: container
            securityContext:
              privileged: true
          volumes:
          - name: var-lib-kubelet
          - name: var-lib-containerd
          - name: var-lib-etcd
          - name: etc-cni
          - name: run
          - name: system
