apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- target:
    group: apps
    version: v1
  patch: |-
    apiVersion: apps/v1
    kind: DoesNotMatter
    metadata:
      name: does-not-matter
    spec:
      template:
        spec:
          initContainers: []
          containers:
          - name: talos
            image: ghcr.io/siderolabs/talos
            ports:
            - containerPort: 50000
              name: talos-api
            volumeMounts:
            - name: var
              mountPath: /var
            - name: var-lib-kubelet
              mountPath: /var/lib/kubelet
            - name: var-lib-containerd
              mountPath: /var/lib/containerd
            - name: var-lib-etcd
              mountPath: /var/lib/etcd
            - name: etc-cni
              mountPath: /etc/cni
            - name: etc-kubernetes
              mountPath: /etc/kubernetes
            - name: run
              mountPath: /run
            - name: system
              mountPath: /system
            - name: opt
              mountPath: /opt
            - name: talos-config
              mountPath: /talos-config
            - name: tmp
              mountPath: /tmp
            env:
            - name: PLATFORM
              value: container
            securityContext:
              privileged: true
              readOnlyRootFilesystem: true
              seccompProfile:
                type: Unconfined
            startupProbe:
              tcpSocket:
                port: 50000
              initialDelaySeconds: 30
              periodSeconds: 30
              timeoutSeconds: 2
              failureThreshold: 6
              successThreshold: 1
            livenessProbe:
              tcpSocket:
                port: 50000
              initialDelaySeconds: 0
              periodSeconds: 30
              timeoutSeconds: 2
              failureThreshold: 3
              successThreshold: 1
          volumes:
          - name: var
          - name: var-lib-kubelet
          - name: var-lib-containerd
          - name: var-lib-etcd
          - name: etc-cni
          - name: etc-kubernetes
          - name: run
          - name: system
          - name: opt
          - name: tmp

- target:
    group: apps
    version: v1
    kind: Deployment
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: worker
    spec:
      template:
        spec:
          containers:
          - name: talos
            readinessProbe:
              tcpSocket:
                port: 50000
              initialDelaySeconds: 0
              periodSeconds: 30
              timeoutSeconds: 2
              failureThreshold: 3
              successThreshold: 1
