apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
commonLabels:
  app.kubernetes.io/name: talos
  app.kubernetes.io/component: node
patches:
- target:
    group: apps
    version: v1
  patch: |-
    apiVersion: apps/v1
    kind: DoesNotMatter
    metadata:
      name: does-not-matter
    spec:
      template:
        spec:
          initContainers:
          - name: get-assets
            image: docker.io/curlimages/curl:7.75.0
            command:
            - sh
            - -ec
            - |-
              curl -L -o /talos/bin/talosctl \
                "https://github.com/talos-systems/talos/releases/download/v0.9.0-beta.1/talosctl-linux-amd64"
              chmod +x /talos/bin/talosctl

              curl -L -o /talos/bin/kubectl \
                "https://dl.k8s.io/release/v1.20.5/bin/linux/amd64/kubectl"
              chmod +x /talos/bin/kubectl
            volumeMounts:
            - name: talos-config
              mountPath: /talos-config
            - name: talos-bin
              mountPath: /talos/bin
          - name: copy-config
            image: docker.io/library/alpine
            command:
            - sh
            - -ec
            - |-
              mkdir -p /system/state
              cp /talos-config/config.yaml /system/state/config.yaml
              cp /talos-config/talosconfig /system/state/talosconfig
            volumeMounts:
            - name: talos-config
              mountPath: /talos-config
            - name: system
              mountPath: /system
          containers:
          - name: talos
            image: ghcr.io/talos-systems/talos
            volumeMounts:
            - name: var-lib-kubelet
              mountPath: /var/lib/kubelet
            - name: var-lib-containerd
              mountPath: /var/lib/containerd
            - name: var-lib-etcd
              mountPath: /var/lib/etcd
            - name: etc-cni
              mountPath: /etc/cni
            - name: run
              mountPath: /run
            - name: system
              mountPath: /system
            - name: talos-bin
              mountPath: /talos/bin
            env:
            - name: PLATFORM
              value: container
            securityContext:
              privileged: true
          volumes:
          - name: var-lib-kubelet
          - name: var-lib-containerd
          - name: var-lib-etcd
          - name: etc-cni
          - name: run
          - name: system
          - name: talos-bin
