apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: config
  literals:
  - CLUSTER_NAME=tink
  - CLUSTER_DOMAIN=tink.local
  - CONTROLPLANE_SERVICE_FQDN=controlplane.default.svc.cluster.local
  - CONTROLPLANE_SERVICE_PORT=6443
  - POD_SUBNETS=["10.244.0.0/16"]
  - SERVICE_SUBNETS=["10.96.0.0/12"]
  - CNI_NAME=flannel
  - CNI_URLS=[]
  - KUBEPROXY_DISABLED=false
  - >-
    ETCD_EXTRA_ARGS={
      "logger": "zap",
      "listen-metrics-urls": "http://0.0.0.0:8080"
    }
  - |-
    CERT_SANS=[
      "127.0.0.1",
      "localhost",
      "controlplane",
      "controlplane.default",
      "controlplane.default.svc",
      "controlplane.default.svc.cluster.local",
      "controlplane-0.controlplane",
      "controlplane-0.controlplane.default",
      "controlplane-0.controlplane.default.svc",
      "controlplane-0.controlplane.default.svc.cluster.local",
      "controlplane-1.controlplane",
      "controlplane-1.controlplane.default",
      "controlplane-1.controlplane.default.svc",
      "controlplane-1.controlplane.default.svc.cluster.local",
      "controlplane-2.controlplane",
      "controlplane-2.controlplane.default",
      "controlplane-2.controlplane.default.svc",
      "controlplane-2.controlplane.default.svc.cluster.local"
    ]
