apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: config
  literals:
  - CLUSTER_NAME=tink
  - CLUSTER_DOMAIN=tink.local
  - CONTROLPLANE_SERVICE_FQDN=controlplane.default.svc.cluster.local
  - CONTROLPLANE_SERVICE_PORT=6443
