apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  template:
    spec:
      initContainers: []
      containers:
      - name: talos
        env:
        - name: USERDATA
          valueFrom:
            secretKeyRef:
              name: mycluster
              key: worker-base64
        volumeMounts:
        - name: talos-config
          mountPath: /talos-config
      volumes:
      - name: talos-config
        secret:
          secretName: tink
          items:
          - key: worker.yaml
            path: config.yaml
          - key: talosconfig
            path: talosconfig
          optional: false
