apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  template:
    spec:
      initContainers: []
      containers:
      - name: talos
        volumeMounts:
        - name: talos-config
          mountPath: /talos-config
      volumes:
      - name: talos-config
        secret:
          secretName: tint
          items:
          - key: join.yaml
            path: config.yaml
          - key: talosconfig
            path: talosconfig
          optional: false
