apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
commonLabels:
  app.kubernetes.io/name: talos
  app.kubernetes.io/component: node
  node-role.kubernetes.io/worker: ""
