apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: talos
    app.kubernetes.io/component: node
    node-role.kubernetes.io/worker: ""
