apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../config
- ../node/controlplane
- ../node/worker
- ../bootstrap
- ../generate-talos-config-secret
components:
- ../node/kustomize-config
- ../node/common
namespace: default
images:
- name: ghcr.io/talos-systems/talos
  newTag: v0.9.0-beta.1
- name: ghcr.io/talos-systems/talosctl
  newTag: v0.10.0-alpha.0-4-g24cd0a20
- name: docker.io/mikefarah/yq
  newTag: 4.6.1
- name: docker.io/bitnami/kubectl
  newTag: 1.20.5
commonLabels:
  app.kubernetes.io/name: talos
  app.kubernetes.io/instance: mycluster
  cluster.x-k8s.io/cluster-name: mycluster

configMapGenerator:
- name: config
  behavior: merge
  literals:
  - CLUSTER_NAME=mycluster
  - CLUSTER_DOMAIN=mycluster.local
  - CONTROLPLANE_SERVICE_FQDN=controlplane.default.svc.cluster.local
  - CONTROLPLANE_SERVICE_PORT=6443

patches:
- target:
    group: apps
    version: v1
    labelselector: app.kubernetes.io/name=talos,app.kubernetes.io/component=node
  patch: |-
    apiVersion: apps/v1
    kind: SomeNode
    metadata:
      name: some-node
    spec:
      template:
        spec:
          volumes:
          - name: talos-config
            secret:
              secretName: mycluster

- target:
    group: batch
    version: v1
    name: bootstrap
  patch: |-
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: bootstrap
    spec:
      template:
        spec:
          volumes:
          - name: talos-config
            secret:
              secretName: mycluster
