apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../node/controlplane
- ../node/worker
- ../bootstrap
- ../generate-talos-config-secret

components:
- ../node/common

images:
- name: ghcr.io/siderolabs/talos
  newTag: v1.7.6
- name: ghcr.io/siderolabs/talosctl
  newTag: v1.7.6
- name: docker.io/mikefarah/yq
  newTag: 4.44.3
- name: docker.io/bitnami/kubectl
  newTag: 1.29.7

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: talos
    app.kubernetes.io/instance: mycluster
    cluster.x-k8s.io/cluster-name: mycluster

configMapGenerator:
- name: config
  behavior: create
  literals:
  - CLUSTER_NAME=mycluster
  - CLUSTER_DOMAIN=mycluster.local
  - CONTROLPLANE_SERVICE_FQDN=controlplane
  - CONTROLPLANE_SERVICE_PORT=6443

patches:
- target:
    group: apps
    version: v1
    labelselector: app.kubernetes.io/name=talos,app.kubernetes.io/component=node
  patch: |-
    apiVersion: apps/v1
    kind: SomeNode
    metadata:
      name: some-node
    spec:
      template:
        spec:
          volumes:
          - name: talos-config
            secret:
              secretName: mycluster

- target:
    group: batch
    version: v1
    name: bootstrap
  patch: |-
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: bootstrap
    spec:
      template:
        spec:
          volumes:
          - name: talos-config
            secret:
              secretName: mycluster
