apiVersion: batch/v1
kind: Job
metadata:
  name: generate-talos-config-secret
spec:
  template:
    spec:
      serviceAccountName: generate-talos-config-secret
      restartPolicy: OnFailure
      volumes:
        - name: talos-config
      initContainers:
      - name: talos-gen-config
        workingDir: /talos-config
        image: ghcr.io/talos-systems/talosctl
        args:
        - gen
        - config
        - $(CLUSTER_NAME)
        - https://$(CONTROLPLANE_SERVICE_FQDN):$(CONTROLPLANE_SERVICE_PORT)
        - --dns-domain=$(CLUSTER_DOMAIN)
        envFrom:
        - configMapRef:
            name: config
        volumeMounts:
        - name: talos-config
          mountPath: /talos-config
      containers:
      - name: kubectl-create-secret
        workingDir: /talos-config
        image: docker.io/bitnami/kubectl
        args:
        - create
        - secret
        - generic
        - $(CLUSTER_NAME)
        - --from-file=controlplane.yaml
        - --from-file=init.yaml
        - --from-file=join.yaml
        - --from-file=talosconfig
        envFrom:
        - configMapRef:
            name: config
        volumeMounts:
        - name: talos-config
          mountPath: /talos-config
