apiVersion: batch/v1
kind: Job
metadata:
  name: generate-talos-config-secret
spec:
  template:
    spec:
      serviceAccountName: generate-talos-config-secret
      restartPolicy: OnFailure
      volumes:
        - name: talos-config
      initContainers:
      - name: talos-gen-config
        workingDir: /talos-config
        image: ghcr.io/siderolabs/talosctl
        args:
        - gen
        - config
        - $(CLUSTER_NAME)
        - https://$(CONTROLPLANE_SERVICE_FQDN):$(CONTROLPLANE_SERVICE_PORT)
        - --with-docs=false
        - --with-examples=false
        - --with-cluster-discovery=false
        - --with-kubespan=false
        - --additional-sans="$(CONTROLPLANE_SERVICE_FQDN)"
        - --additional-sans="localhost"
        # See: https://www.talos.dev/v1.7/talos-guides/install/cloud-platforms/kubernetes/#machine-configuration
        - |-
            --config-patch=
              [
                 {
                    "op":"add",
                    "path":"/machine/features/hostDNS/forwardKubeDNSToHost",
                    "value":true
                 },
                 {
                    "op":"add",
                    "path":"/machine/features/hostDNS/resolveMemberNames",
                    "value":true
                 },
                 {
                    "op":"add",
                    "path":"/machine/features/kubePrism",
                    "value": {"enabled": false}
                 },
                 {
                    "op":"replace",
                    "path":"/cluster/network/podSubnets",
                    "value": ["172.16.0.1/16"]
                 },
                 {
                    "op":"replace",
                    "path":"/cluster/network/serviceSubnets",
                    "value": ["172.17.0.1/16"]
                 }
              ]
        - --dns-domain=$(CLUSTER_DOMAIN)
        envFrom:
        - configMapRef:
            name: config
        volumeMounts:
        - name: talos-config
          mountPath: /talos-config
      - name: base64-encode
        workingDir: /talos-config
        image: docker.io/library/alpine
        command:
        - sh
        - -ec
        - |-
            cat controlplane.yaml | base64 > controlplane-base64
            cat worker.yaml | base64 > worker-base64
        envFrom:
        - configMapRef:
            name: config
        volumeMounts:
        - name: talos-config
          mountPath: /talos-config
      containers:
      - name: kubectl-create-secret
        workingDir: /talos-config
        image: docker.io/bitnami/kubectl
        args:
        - create
        - secret
        - generic
        - $(CLUSTER_NAME)
        - --from-file=controlplane.yaml
        - --from-file=worker.yaml
        - --from-file=controlplane-base64
        - --from-file=worker-base64
        - --from-file=talosconfig
        envFrom:
        - configMapRef:
            name: config
        volumeMounts:
        - name: talos-config
          mountPath: /talos-config
