apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- job.yaml
- role.yaml
- rolebinding.yaml
- serviceaccount.yaml
commonLabels:
  cluster.x-k8s.io/cluster-name: my-cluster
  app.kubernetes.io/component: bootstrap
