apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- job.yaml
- role.yaml
- rolebinding.yaml
- serviceaccount.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: generate-talos-config-secret
