apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: generate-talos-config-secret
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: generate-talos-config-secret
subjects:
- kind: ServiceAccount
  name: generate-talos-config-secret
