apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yaml
- service.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: talos
    app.kubernetes.io/component: node
    node-role.kubernetes.io/control-plane: ""
