apiVersion: v1
kind: Service
metadata:
  name: controlplane
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: kube-api
    port: 6443
    protocol: TCP
    targetPort: 6443
  - name: talos-api
    port: 50000
    protocol: TCP
    targetPort: 50000
