apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controlplane
spec:
  serviceName: controlplane
  template:
    spec:
      subdomain: controlplane
      initContainers: []
      containers:
      - name: talos
        ports:
        - containerPort: 6443
          name: kube-api
        - containerPort: 50000
          name: talos-api
        lifecycle:
          preStop:
            exec:
              command:
              - /talos/bin/talosctl
              - --talosconfig=/system/state/talosconfig
              - --endpoints=localhost
              - --nodes=localhost
              - etcd
              - leave
      volumes:
      - name: talos-config
        secret:
          secretName: tint
          items:
          - key: controlplane.yaml
            path: config.yaml
          - key: talosconfig
            path: talosconfig
          optional: false
