apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controlplane
spec:
  serviceName: controlplane
  template:
    spec:
      subdomain: controlplane
      initContainers: []
      containers:
      - name: talos
        env:
        - name: USERDATA
          valueFrom:
            secretKeyRef:
              name: mycluster
              key: controlplane-base64
        ports:
        - containerPort: 6443
          name: kube-api
      volumes:
      - name: talos-config
        secret:
          secretName: tink
          items:
          - key: controlplane.yaml
            path: config.yaml
          - key: talosconfig
            path: talosconfig
          optional: false
