apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controlplane
spec:
  serviceName: controlplane
  template:
    spec:
      initContainers: []
      containers:
      - name: talos
        ports:
        - containerPort: 6443
          name: kube-api
        - containerPort: 50000
          name: talos-api
        volumeMounts:
        - name: talos-config
          mountPath: /talos-config
      volumes:
      - name: talos-config
        secret:
          secretName: tint
          items:
          - key: controlplane.yaml
            path: config.yaml
          optional: false
